### ISSUE TITLE
[URGENT] It refuse to install with the latest NodeJS 0.12.2 on Ubuntu Server

### ISSUE THREAD

**Issue by MrBokeh** [lloyd/node-toobusy#47]
# Here is the error:

> toobusy@0.2.4 install /root/node_modules/toobusy
> node-gyp rebuild

make: Entering directory `/root/node_modules/toobusy/build'
  CXX(target) Release/obj.target/toobusy/toobusy.o
make: g++: Command not found
make: *** [Release/obj.target/toobusy/toobusy.o] Error 127
make: Leaving directory`/root/node_modules/toobusy/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/toobusy
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "toobusy@latest"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! toobusy@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the toobusy@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the toobusy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls toobusy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by gigablah** [comment]
There's your issue: `g++: Command not found`

Try

```
sudo apt-get update
sudo apt-get install build-essential
```
